title: Whisper
description: Reference website for the app Whisper
theme: just-the-docs

url: https://whisper-project.github.io/client.swift

plugins:
  - jekyll-relative-links

mermaid:
  version: 10.3

aux_links:
  ClickOneTwo: 
    - "https://clickonetwo.io"

aux_links_new_tab: true
