title: Whisper
description: Reference website for the app Whisper
theme: just-the-docs

url: https://whisper-project.github.io/client.swift

plugins:
  - jekyll-relative-links

mermaid:
  version: 10.3

aux_links:
  "Whisper Project": 
    - "http://whisper-project.org"

aux_links_new_tab: true
